name: aws core api deployment
on:
  push:
    branches:
      - develop*
      - feature/hospital-backend
    # paths:
    #   - core/**
env:
  CORE_PATH: core
  CDK_PATH: hospitals-backend
jobs:
  build_cdk:
    name: build - cdk
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.12"
      - name: install
        working-directory: ${{env.CDK_PATH}}
        run: npm i
      - name: build
        working-directory: ${{env.CDK_PATH}}
        run: npm run build
  build_and_test_core:
    name: build - core
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.10.1"
      - name: install
        working-directory: ${{env.CORE_PATH}}
        run: npm i
      - name: build
        working-directory: ${{env.CORE_PATH}}
        run: npm run build
      - name: test
        working-directory: ${{env.CORE_PATH}}
        run: npm run test

  deploy:
    name: deploy
    needs: [build_cdk, build_and_test_core]
    runs-on: ubuntu-18.04
    steps:
      - uses: youyo/aws-cdk-github-actions@master
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: ${{env.CDK_PATH}}
          actions_comment: false
          args: '--require-approval never'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          AWS_ACCESS_KEY_SECRET: ${{ secrets.TEST_AWS_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
